// <auto-generated />
using Carvajal.Infraestructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Carvajal.Infraestructure.Data.Migrations
{
    [DbContext(typeof(CarvajalDbContext))]
    [Migration("20210410210019_v1.1")]
    partial class v11
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Carvajal.Domain.Models.TypeIdentification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(120)")
                        .HasMaxLength(120);

                    b.HasKey("Id");

                    b.ToTable("TypeIdentification");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "CC - Cedula Ciudadania"
                        },
                        new
                        {
                            Id = 2,
                            Description = "RC - Registro Civil"
                        },
                        new
                        {
                            Id = 3,
                            Description = "TI - Tarjeta Identidad"
                        },
                        new
                        {
                            Id = 4,
                            Description = "CE - Cedula Extrajera"
                        },
                        new
                        {
                            Id = 5,
                            Description = "PA - Pasaporte"
                        });
                });

            modelBuilder.Entity("Carvajal.Domain.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("Identification")
                        .IsRequired()
                        .HasColumnType("nvarchar(21)")
                        .HasMaxLength(21);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<int>("TypeIdentificationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TypeIdentificationId");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "ltsa0314@gmail.com",
                            Identification = "1110544973",
                            LastName = "Sanchez Arevalo",
                            Name = "Leidy Tatina",
                            Password = "Tatiana@2021",
                            TypeIdentificationId = 1
                        });
                });

            modelBuilder.Entity("Carvajal.Domain.Models.User", b =>
                {
                    b.HasOne("Carvajal.Domain.Models.TypeIdentification", "TypeIdentification")
                        .WithMany("Users")
                        .HasForeignKey("TypeIdentificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
